# Generated by Django 4.2.9 on 2024-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
